//! Handcrafted HSA ABI types used by the KFD-direct path.
//!
//! Tinygrad uses ctypes-autogenerated bindings from `hsa.h`; we lift only the
//! structs and constants we actually need so we don't pull a libhsa-runtime64
//! dependency. Layouts are taken from the HSA Platform System Architecture
//! Specification §2.8 (Packet Layout).

#![allow(dead_code)]

use std::mem::size_of;

/// Opaque HSA signal handle (in the KFD-direct model this is the GPU virtual
/// address of the timeline signal slot).
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct HsaSignal {
    pub handle: u64,
}

/// HSA `kernel_dispatch_packet_t`. The AQL ring is an array of these (64 B
/// each). Fields match `hsa.h` exactly.
#[repr(C, align(64))]
#[derive(Debug, Clone, Copy, Default)]
pub struct HsaKernelDispatchPacket {
    pub header: u16,
    pub setup: u16,
    pub workgroup_size_x: u16,
    pub workgroup_size_y: u16,
    pub workgroup_size_z: u16,
    pub reserved0: u16,
    pub grid_size_x: u32,
    pub grid_size_y: u32,
    pub grid_size_z: u32,
    pub private_segment_size: u32,
    pub group_segment_size: u32,
    pub kernel_object: u64,
    pub kernarg_address: u64,
    pub reserved2: u64,
    pub completion_signal: HsaSignal,
}

const _PACKET_SIZE_IS_64: () = assert!(size_of::<HsaKernelDispatchPacket>() == 64);

// ── Packet header bit positions ──────────────────────────────────────────
pub const HSA_PACKET_HEADER_TYPE: u16 = 0;
pub const HSA_PACKET_HEADER_BARRIER: u16 = 8;
pub const HSA_PACKET_HEADER_SCACQUIRE_FENCE_SCOPE: u16 = 9;
pub const HSA_PACKET_HEADER_SCRELEASE_FENCE_SCOPE: u16 = 11;

// ── Packet type values ───────────────────────────────────────────────────
pub const HSA_PACKET_TYPE_VENDOR_SPECIFIC: u16 = 0;
pub const HSA_PACKET_TYPE_INVALID: u16 = 1;
pub const HSA_PACKET_TYPE_KERNEL_DISPATCH: u16 = 2;
pub const HSA_PACKET_TYPE_BARRIER_AND: u16 = 3;
pub const HSA_PACKET_TYPE_AGENT_DISPATCH: u16 = 4;
pub const HSA_PACKET_TYPE_BARRIER_OR: u16 = 5;

// ── Fence scopes ─────────────────────────────────────────────────────────
pub const HSA_FENCE_SCOPE_NONE: u16 = 0;
pub const HSA_FENCE_SCOPE_AGENT: u16 = 1;
pub const HSA_FENCE_SCOPE_SYSTEM: u16 = 2;

/// Convenience: build the `header` field for a kernel-dispatch packet with
/// system-scope acquire+release fences (matches tinygrad `AQL_HDR` at
/// `ops_amd.py:32-33`).
pub const fn kernel_dispatch_header() -> u16 {
    HSA_PACKET_TYPE_KERNEL_DISPATCH
        | (1 << HSA_PACKET_HEADER_BARRIER)
        | (HSA_FENCE_SCOPE_SYSTEM << HSA_PACKET_HEADER_SCACQUIRE_FENCE_SCOPE)
        | (HSA_FENCE_SCOPE_SYSTEM << HSA_PACKET_HEADER_SCRELEASE_FENCE_SCOPE)
}

/// AMDGPU kernel descriptor (64 bytes), stored in the code object's
/// `.rodata.kernel.desc` segment. Layout per AMDGPU ABI v5. We read this out
/// of the loaded ELF when constructing an `AmdProgram` (Phase 6).
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, Default)]
pub struct AmdHsaKernelDescriptor {
    pub group_segment_fixed_size: u32,      // off  0..4
    pub private_segment_fixed_size: u32,    // off  4..8
    pub kernarg_size: u32,                  // off  8..12
    pub _reserved0: [u8; 4],                // off 12..16
    pub kernel_code_entry_byte_offset: i64, // off 16..24
    pub _reserved1: [u8; 20],               // off 24..44
    pub compute_pgm_rsrc3: u32,             // off 44..48
    pub compute_pgm_rsrc1: u32,             // off 48..52
    pub compute_pgm_rsrc2: u32,             // off 52..56
    pub kernel_code_properties: u16,        // off 56..58 (bit 10 = wave32)
    pub _reserved2: [u8; 6],                // off 58..64
}

const _DESC_SIZE_IS_64: () = assert!(size_of::<AmdHsaKernelDescriptor>() == 64);

/// kernel_code_properties bit: enable wave32 dispatch (clear for wave64).
pub const ENABLE_WAVEFRONT_SIZE32: u16 = 1 << 10;

/// `kernel_code_properties` bits that affect the User SGPR pre-load layout —
/// each enabled bit prepends/appends slots to `COMPUTE_USER_DATA_0..N` that
/// the kernel reads via `s_load_*`. Tinygrad refers to these as
/// `AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_*` (autogen/hsa.py).
pub const ENABLE_SGPR_PRIVATE_SEGMENT_BUFFER: u16 = 1 << 0; // 4 SGPRs
pub const ENABLE_SGPR_DISPATCH_PTR: u16 = 1 << 1; // 2 SGPRs
pub const ENABLE_SGPR_KERNARG_SEGMENT_PTR: u16 = 1 << 3; // 2 SGPRs

// ── amd_queue_t (256-byte queue descriptor stored in GART) ───────────────
//
// Field layout extracted from tinygrad's `runtime/autogen/hsa.py` ctypes
// dump. The kernel-mode driver reads this struct when initializing the AQL
// queue, so it must be valid before `AMDKFD_IOC_CREATE_QUEUE` is called.

#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct HsaQueue {
    pub kind: u32,            // off 0
    pub features: u32,        // off 4
    pub base_address: u64,    // off 8
    pub doorbell_signal: u64, // off 16
    pub size: u32,            // off 24
    pub reserved0: u32,       // off 28
    pub id: u64,              // off 32
}

#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct AmdQueueT {
    pub hsa_queue: HsaQueue,                          // off  0..40
    pub caps: u32,                                    // off 40
    pub reserved1: [u32; 3],                          // off 44
    pub write_dispatch_id: u64,                       // off 56
    pub group_segment_aperture_base_hi: u32,          // off 64
    pub private_segment_aperture_base_hi: u32,        // off 68
    pub max_cu_id: u32,                               // off 72
    pub max_wave_id: u32,                             // off 76
    pub max_legacy_doorbell_dispatch_id_plus_1: u64,  // off 80
    pub legacy_doorbell_lock: u32,                    // off 88
    pub reserved2: [u32; 9],                          // off 92
    pub read_dispatch_id: u64,                        // off 128
    pub read_dispatch_id_field_base_byte_offset: u32, // off 136
    pub compute_tmpring_size: u32,                    // off 140
    pub scratch_resource_descriptor: [u32; 4],        // off 144
    pub scratch_backing_memory_location: u64,         // off 160
    pub reserved3: [u32; 2],                          // off 168
    pub scratch_wave64_lane_byte_size: u32,           // off 176
    pub queue_properties: u32,                        // off 180
    pub reserved4: [u32; 2],                          // off 184
    pub queue_inactive_signal: HsaSignal,             // off 192
    pub reserved5: [u32; 14],                         // off 200
}

const _AMD_QUEUE_T_IS_256: () = assert!(std::mem::size_of::<AmdQueueT>() == 256);

/// Byte offset of `read_dispatch_id` inside `AmdQueueT`. KFD's create_queue
/// expects rptr/wptr at fixed offsets within the GART descriptor.
pub const OFFSET_READ_DISPATCH_ID: usize = 128;
pub const OFFSET_WRITE_DISPATCH_ID: usize = 56;

// queue_properties bits.
pub const AMD_QUEUE_PROPERTIES_IS_PTR64: u32 = 1 << 0;
pub const AMD_QUEUE_PROPERTIES_ENABLE_PROFILING: u32 = 1 << 1;
