//! Bindgen-generated KFD ioctl bindings.
//!
//! On Linux this is generated by `build.rs` from `include/kfd_ioctl.h`. On
//! other platforms it's an empty stub so the module compiles unconditionally
//! (AMD codepaths fail with `Error::NoAmdGpu` at runtime).

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::missing_safety_doc
)]

include!(concat!(env!("OUT_DIR"), "/kfd_sys.rs"));
