#!/usr/bin/env python3
"""One-shot generator for the AM driver's register tables.

Parses tinygrad's `autogen/am/regs.py` (a self-contained set of per-IP-version
dicts) and emits a VENDORED Rust source file `device/src/amd/am/regs_gen.rs`.
This is run MANUALLY when adding/updating an arch — the cargo build never
touches tinygrad (which is a sometimes-absent submodule). Re-run + commit the
output.

    python3 device/tools/gen_am_regs.py \
        [path/to/tinygrad/runtime/autogen/am] \
        [device/src/amd/am/regs_gen.rs]

Each tinygrad register is `name -> (offset, segment, {field: (lo, hi)})`; we
emit `RegDef { name, offset, segment, fields: &[RegField{name, lo, hi}] }` plus
an `AM_REG_MODULES` table of `(prefix, (maj,min,rev), &[RegDef])` that
`regs.rs::select` resolves by the discovered `ip_ver`.
"""
import importlib.util
import os
import sys

# (rust_static_name, regs.py module attr, prefix, (maj, min, rev))
# gfx1151 / Strix Halo target set (see memory amd-hw-is-strix-halo-gfx1151-apu).
# Widen this list + re-run to add another arch.
MODULES = [
    ("GC_11_5_0", "gc_11_5_0", "gc", (11, 5, 0)),
    ("MMHUB_3_3_0", "mmhub_3_3_0", "mmhub", (3, 3, 0)),
    ("MP_14_0_2", "mp_14_0_2", "mp", (14, 0, 2)),
    ("NBIO_7_11_0", "nbio_7_11_0", "nbio", (7, 11, 0)),
    ("HDP_6_0_0", "hdp_6_0_0", "hdp", (6, 0, 0)),
    ("OSSSYS_6_0_0", "osssys_6_0_0", "osssys", (6, 0, 0)),
]


def load_regs(autogen_dir: str):
    path = os.path.join(autogen_dir, "regs.py")
    spec = importlib.util.spec_from_file_location("am_regs", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.dirname(os.path.dirname(here))
    autogen_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        repo, "submodules/new_new_tinygrad/tinygrad/runtime/autogen/am")
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        repo, "device/src/amd/am/regs_gen.rs")

    regs = load_regs(autogen_dir)
    lines = [
        "// @generated by device/tools/gen_am_regs.py from tinygrad autogen/am/regs.py.",
        "// DO NOT EDIT BY HAND. Re-run the generator (manually) to update.",
        "// Vendored so the build never depends on the tinygrad submodule.",
        "",
    ]
    total_regs = 0
    for static_name, attr, _prefix, _ver in MODULES:
        table = getattr(regs, attr)
        lines.append(f"/// `{attr}` — {len(table)} registers.")
        lines.append(f"pub static {static_name}: &[RegDef] = &[")
        for name, (offset, segment, fields) in table.items():
            fs = "".join(
                f"RegField{{name:{f!r},lo:{lo},hi:{hi}}}," for f, (lo, hi) in fields.items()
            ).replace("'", '"')
            lines.append(
                f'    RegDef{{name:{name!r},offset:{offset},segment:{segment},fields:&[{fs}]}},'.replace("'", '"')
            )
        lines.append("];")
        lines.append("")
        total_regs += len(table)

    lines.append("/// All vendored register modules, resolved by `regs::select(prefix, ip_ver)`.")
    lines.append("pub static AM_REG_MODULES: &[RegModule] = &[")
    for static_name, _attr, prefix, (maj, mn, rev) in MODULES:
        lines.append(f'    ("{prefix}", ({maj}, {mn}, {rev}), {static_name}),')
    lines.append("];")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path}: {len(MODULES)} modules, {total_regs} registers")


if __name__ == "__main__":
    main()
